#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define ENABLE_RGB_MATRIX_STARLIGHT

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_STARLIGHT
// #undef INVERT_OS_SWITCH_STATE
#define TAPPING_TOGGLE 2


#undef ENABLE_FACTORY_TEST
